name: Release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_name:
        description: Name of the release
        required: true

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust: [stable]
        include:
        - os: macos-latest
          artifact_prefix: macos
          target: x86_64-apple-darwin
        - os: ubuntu-latest
          artifact_prefix: linux
          target: x86_64-unknown-linux-gnu
    steps:
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "${{ matrix.rust }}"
        override: true
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Execute cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        toolchain: "${{ matrix.rust }}"
        args: --release --target "${{ matrix.target }}"
    - name: Package final binary
      shell: bash
      run: |
        cd "target/${{ matrix.target }}/release"
        strip ksrt
        tar czvf "ksrt-${{ matrix.artifact_prefix }}.tar.gz" ksrt
        shasum -a 256 "ksrt-${{ matrix.artifact_prefix }}.tar.gz" > "ksrt-${{ matrix.artifact_prefix }}.sha256"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "ksrt-${{ matrix.artifact_prefix }}"
        path: "target/${{ matrix.target }}/release/"

  build-rpm:
    name: Build rpm packages
    needs: build
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        include:
        - os: ubuntu-latest
          artifact_prefix: linux
          target: x86_64-unknown-linux-gnu
    steps:
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "${{ matrix.rust }}"
        override: true
    - name: Install cargo-rpm
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-rpm
        version: latest
        use-tool-cache: true
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: "ksrt-${{ matrix.artifact_prefix }}"
        path: "target/release"
    - name: Execute cargo rpm build
      uses: actions-rs/cargo@v1
      with:
        command: rpm
        toolchain: "${{ matrix.rust }}"
        args: build -v --no-cargo-build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "ksrt-rpm"
        path: "target/release/rpmbuild/RPMS/x86_64/"

  build-deb:
    name: Build deb packages
    needs: build
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        include:
        - os: ubuntu-latest
          artifact_prefix: linux
          target: x86_64-unknown-linux-gnu
    steps:
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "${{ matrix.rust }}"
        override: true
    - name: Install cargo-deb
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-deb
        version: latest
        use-tool-cache: true
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: "ksrt-${{ matrix.artifact_prefix }}"
        path: "target/release"
    - name: Execute cargo deb
      uses: actions-rs/cargo@v1
      with:
        command: deb
        toolchain: "${{ matrix.rust }}"
        args: -v --no-build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "ksrt-deb"
        path: "target/debian/"

  release:
    name: Create release
    needs: [build, build-rpm, build-deb]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_name || github.ref }}
        files: |
          ksrt-*/ksrt-*.tar.gz
          ksrt-*/ksrt-*.sha256
          ksrt-*/ksrt-*.rpm
          ksrt-*/ksrt_*.deb
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#   publish:
#     name: Publishing to Crates.io
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - uses: actions-rs/toolchain@v1
#       with:
#         toolchain: stable
#         override: true
#     - uses: actions-rs/cargo@v1
#       with:
#         command: publish
#         args: --token {{ "${{ secrets.CARGO_API_KEY " }}}} --allow-dirty
